music_directory         "~/media/Music"
playlist_directory	"~/media/Music/Playlists"
db_file			"~/.cache/mpd/database"
sticker_file		"~/.cache/mpd/stickers"
port		        "6600"

auto_update "yes"

input {
        plugin "curl"
}

decoder {
        plugin "fluidsynth"
        soundfont "~/media/Music/Midi/Soundfonts/Shadow 1.0.sf2"
}

audio_output {
        type "pipewire"
        name "alsa_output.pci-0000_00_1f.3.analog-stereo"
        mixer_type "software"

        #these are "alsa" options
        #auto_resample    "no"
        #auto_format      "no"
        #auto_channels    "no"
}
replaygain "track"

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}
