"$schema" = "https://starship.rs/config-schema.json"
palette = "catppuccin_latte"
format = "[$fill](fg:pink) $os$username$hostname[$fill](fg:pink)$line_break[ ]()$all[$fill](hidden) $cmd_duration$time[[ ](bg:#5bcffa)[ ](bg:#ffb5cd)[ ](bg:#ffffff)[ ](bg:#ffb5cd)[ ](bg:#5bcffa) ](bold)$line_break[ ]()$character"
right_format = "$status$shlvl$shell[ ]()$container"
add_newline = false
command_timeout = 2000

[fill]
symbol = "─"
style = "none"

[line_break]
disabled = false

[character]
format = "$symbol"
vimcmd_symbol = "[❮](green)"

[sudo]
disabled = false
allow_windows = true
format = "[$symbol]($style)"

[os]
format = "[$symbol]($style)"
disabled = false

[os.symbols]
Alpaquita = "[ ](fg:#85d888 blink)"
Alpine = "[ ](fg:#0d597f blink)"
Amazon = "[ ](fg:#ff9a00 blink)"
Android = "[ ](fg:#a5c736 blink)"
Arch = "[ ](fg:#1787c1 blink)"
Artix = "[ ](fg:#07a2cd blink)"
CentOS = "[ ](fg:#98277b blink)"
Debian = "[ ](fg:#d70751 blink)"
DragonFly = "[ ](fg:#50bc5d blink)"
Emscripten = "[ ](fg:#b4d234 blink)"
EndeavourOS = "[ ](fg:#803dc0 blink)"
Fedora = "[ ](fg:#50a4db blink)"
FreeBSD = "[ ](fg:#ff0000 blink)"
Garuda = "[󰛓 ](fg:#288feb blink)"
Gentoo = "[ ](fg:#9991da blink)"
HardenedBSD = "[󰞌 ](fg:#2fbef2 blink)"
Illumos = "[󰈸 ](fg:#ff4106 blink)"
Linux = "[ ](fg:#f4bd19 blink)"
Mabox = "[ ](fg:#35bf5c blink)"
Macos = "[ ](fg:#2e2e2e blink)"
Manjaro = "[ ](fg:#32c05c blink)"
Mariner = "[ ](fg:#00a6ef blink)"
MidnightBSD = "[ ](fg:#000000 blink)"
Mint = "[ ](fg:#69b63d blink)"
NetBSD = "[ ](fg:#f26708 blink)"
NixOS = "[ ](fg:#4d71ba blink)"
OpenBSD = "[󰈺 ](fg:#f2cb2c blink)"
openSUSE = "[ ](fg:#6fb424 blink)"
OracleLinux = "[󰌷 ](fg:#ec252e blink)"
Pop = "[ ](fg:#46b3c1 blink)"
Raspbian = "[ ](fg:#b51040 blink)"
Redhat = "[ ](fg:#e70000 blink)"
RedHatEnterprise = "[ ](fg:#e70000 blink)"
Redox = "[󰀘 ](fg:#000000 blink)"
Solus = "[󰠳 ](fg:#4c5263 blink)"
SUSE = "[ ](fg:#79bc43 blink)"
Ubuntu = "[ ](fg:#d64613 blink)"
Unknown = "[ ](fg:#a9a9a9 blink)"
Windows = "[󰍲 ](fg:#01beff blink)"

[directory]
read_only = " 󰌾"
truncation_length = 3
format = "[󱃪 ](yellow)[$path]($style)[$read_only]($read_only_style) "
style = "bold blue"
use_os_path_sep = true

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration ]($style)"
style = "bold lavender"

[username]
style_user = "pink bold"
style_root = "pink bold"
format = "[$user](fg:pink blink)[@](blink)"
disabled = false
show_always = true

[hostname]
disabled = false
ssh_only = false
ssh_symbol = "󰢩 "
style = "pink"
format = "[$ssh_symbol$hostname](fg:pink blink) "

[time]
disabled = false
format = "[ $time]($style) "
style = "bold yellow"

[status]
disabled = false
style = "bold red"
format = "[$symbol$status]($style) "
map_symbol = true

[shell]
disabled = false
format = "[$indicator]($style)"

[shlvl]
disabled = false
symbol = " "
format = "[$symbol$shlvl]($style) "

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]

[git_commit]
tag_symbol = "󰓹 "

[git_metrics]
disabled = true
format = "([ $added]($added_style) )([ $deleted]($deleted_style) )"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
